---
name: "SLURM"
partition: "accelerated"
job-name: "hopper_seq_entire"
num_parallel_jobs: 120
ntasks: 1
cpus-per-task: 152
time: 1500
gpus_per_rep: 1
scheduler: horeka
sbatch_args:
  gres: "gpu:4"

experiment_copy_src:
  - "../" # RL Code base
experiment_copy_auto_dst: "../../CODE_COPY/"
---
name: hopper_seq_entire
import_path: "./shared_hopper.yaml"
import_exp: "hopper_seq_entire"

# cw2 config
repetitions: 8      # Number of repetitions, each with different random seed, 4 for test, 20 for paper
reps_per_job: 4
reps_in_parallel: 4
iterations: &iterations 15000
num_checkpoints: 1

# Hardware specific parameters
params:
  sampler:
    args:
      num_env_train: 1
      num_env_test: 38
      episodes_per_train_env: 1
      episodes_per_test_env: 4
  projection:
    args:
      total_train_steps: *iterations
  reference_split:
    n_splits: 3

grid:
  reference_split:
    ranges: [ [ 125, 75, 50 ] ]